// content/projects/dear___.js developed by Bob Tianqi Wei
module.exports = {
  slug: "dear___",
  content: {
    title: "dear___",
    description: "dear___ is a mobile memory album that uses ephemeral reveal to make encounters with personal photo archives partial, temporary, and reversible.",
    hero: {
      headline: "A mobile memory album that lets people approach emotionally charged photographs slowly, partially, and temporarily.",
      metaLines: [
        "Bob Tianqi Wei and Hiroshi Ishii",
        "MIT Media Lab",
        "Research · Interaction Design · iOS Development · 2026"
      ]
    },
    sections: [
      {
        bodyHtml: "<p>In April 2026, I learned I was moving to Boston for MIT. My partner and I decided to part ways. The distance and the years ahead were too much to ask of each other.</p><p>In the months that followed, I found myself living inside what Hiroshi Ishii calls TeleAbsence: picking up objects my partner had touched, looking at old photographs, feeling a presence slowly becoming absence.</p><p>So I built something — a private photo album of 48 photographs from our years together, with every person masked under a white cover generated by a computer vision model, alongside 48 short texts addressed to my partner across time, and music they had once sent me. Opening the album, I'd see only ghosted figures in familiar places. Erasing a mask brought the figure back, the text surfaced, the music began. Then, after a pause, the mask slowly returned, and presence became absence again.</p><p>I hadn't set out to build an app. I was trying to hold something I didn't yet have words for, talking to someone I loved across time, and through that, to an earlier version of myself.</p><p>I showed it to a close friend once. She watched the figures fade from the photographs, and she cried. So did I.</p><p>That reaction told me the interaction itself — the erasure, the slow return of absence, the layering of image, text, and music, might mean something beyond my own archive. dear___ grew from that instinct.</p>"
      },
      {
        title: "The Idea",
        bodyHtml: "<p>Personal photo archives make memories immediately visible. But after loss or separation, seeing a photograph can bring past closeness back all at once, intensified by the pain of present absence.</p><p>dear___ explores another way of encountering personal memories. Instead of permanently displaying or deleting a photograph, users can cover people or regions with editable white masks, reveal them through touch, and watch the mask gradually return.</p>",
        video: {
          src: "https://www.youtube.com/embed/keVKziKvyEw?si=Vzl8lhm1TruQulvv",
          title: "dear___ demo video",
          allow: "accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
        }
      },
      {
        title: "Ephemeral Reveal",
        bodyHtml: "<style>.dear-theme-image-dark{display:none!important}html[data-theme=\"dark\"] .dear-theme-image-light{display:none!important}html[data-theme=\"dark\"] .dear-theme-image-dark{display:block!important}</style><p>dear___ treats absence as an interactive material through a five-stage interaction.</p><p><strong>Compose</strong><br>Add a photograph, diary entry, music, and time.</p><p><strong>Mask</strong><br>Create and edit a white cover over a person or region.</p><p><strong>Touch Reveal</strong><br>Erase the mask through touch.</p><p><strong>Presence Appears</strong><br>The photograph, diary text, and music emerge together.</p><p><strong>Absence Returns</strong><br>The mask gradually restores itself.</p><figure class=\"project-figure dear-theme-figure\"><img src=\"/images/dear-flow-light.png\" loading=\"lazy\" alt=\"dear___ interaction flow from composing a memory to the return of its mask\" class=\"project-figure-image dear-theme-image dear-theme-image-light\"><img src=\"/images/dear-flow-dark.png\" loading=\"lazy\" alt=\"dear___ interaction flow on a dark background\" class=\"project-figure-image dear-theme-image dear-theme-image-dark\"><figcaption class=\"image-description\">Compose, mask, touch reveal, presence appears, and absence returns.</figcaption></figure>"
      },
      {
        title: "Designing the Memory Object",
        rows: [
          {
            left: {
              bodyHtml: "<p><strong>Compose a Memory Object</strong><br>Each memory in dear___ is more than a photograph. It can contain a mask, diary text, music, temporal metadata, and interaction state. Together, these layers form a personal memory object that can be edited and revisited over time.</p><p><strong>Computer Vision Suggests. The User Decides.</strong><br>dear___ can generate an initial cover using foreground or person segmentation. The result remains fully editable: users can paint, erase, undo, and reshape the mask. Automation accelerates the process without deciding what absence should look like.</p><p><strong>The Reveal Is Temporary</strong><br>In most reveal interfaces, the cover is something to remove. In dear___, re-covering is equally important. The memory can be approached without being permanently exposed. Presence and absence remain in motion within the same artifact.</p><p><strong>Memory Across Time</strong><br>Memories can be found through browsing, but they can also return through time. dear___ uses photo dates, edit dates, “on this day” reminders, and weekly prompts to resurface past moments without pretending to restore the person or relationship itself.</p><p><strong>Consent-Aware Sharing</strong><br>A private memory does not need to become fully public. When users save, share, or submit a memory, they choose which layers may leave the private archive.</p>"
            },
            right: {
              bodyHtml: "<figure class=\"project-figure\"><img src=\"/images/dear-consent-sharing.png\" loading=\"lazy\" alt=\"Consent-aware sharing controls in dear___\" class=\"project-figure-image\" style=\"width:auto;max-height:360px;margin:0 auto\"><figcaption class=\"image-description\">Users choose which layers may leave the private archive.</figcaption></figure>"
            }
          }
        ]
      },
      {
        title: "Usage Scenario",
        bodyHtml: "<p>Eli is navigating the end of a close relationship. He does not want to delete the photographs, songs, and messages that remain, but seeing them fully in an ordinary gallery makes the happiness of the past return all at once, sharpened by the pain of present absence.</p><p>He creates an album in dear___, imports a small group of photographs, and places white masks over the person who is no longer present. He adjusts each mask by hand, writes short notes that read like diary entries or unsent letters, and attaches songs that still carry the shape of that time.</p><p>Later, Eli opens the album. Familiar places appear first—a doorway, a table, a corner of a room—while the person remains covered as a white silhouette. He slowly erases part of the mask. As the figure emerges, the diary text becomes visible and the music begins. After a short pause, the mask returns, and the memory settles back into absence.</p><p>The interaction does not restore the person or erase them. It gives Eli a controlled way to approach their traces, sit with what remains, and address them across time rather than all at once. Over repeated visits, composing masks, writing unsent letters, and watching covers return become small reflective rituals.</p>"
      },
      {
        title: "Technical Implementation",
        bodyHtml: "<p>dear___ is a native SwiftUI iOS application. Each local memory object can contain a photograph, editable mask, title, diary text, audio or music reference, photo date, edit date, and export metadata. Apple's Vision APIs assist with foreground or person segmentation, while manual paint and erase tools keep the final mask under user control. The app also supports touch-based reveal and restoration, temporal reminders, share-card rendering, portable album data, and consent-aware export.</p>"
      },
      {
        title: "Publication",
        publications: [
          {
            title: "dear___: Ephemeral Reveal for Interactive Absence in Personal Photo Archives",
            authors: "Bob Tianqi Wei and Hiroshi Ishii",
            venue: "UIST 2026 demo",
            status: "SUBMITTED",
            abstract: "Personal photo archives preserve traces of people, places, and moments, but they often make memory access fast, flat, and fully visible. For emotionally charged memories, immediate visibility may not always be the desired mode of interaction. We present dear___, a mobile memory album that explores ephemeral reveal as an interaction pattern for TeleAbsence. In dear___, users compose personal photos with editable white masks, diary text, music, and temporal metadata. A user can erase the mask through touch to reveal the photograph and its associated layers; after a short interval, the mask gradually returns, making the encounter partial, temporary, and reversible. The system also supports computer-vision-assisted mask generation, manual cover editing, memory notifications, share cards, and consent-aware export. Rather than simulating an absent person, dear___ works with existing traces and lets users decide how presence should briefly appear, fade, and return to absence. This demo contributes a working mobile system and interaction concept for designing absence as an interactive material in personal photo archives."
          }
        ]
      },
      {
        title: "Project Links",
        bodyHtml: "<p><a href=\"/works/dear___/privacy/\" class=\"link-in-paragraph\">Privacy Policy</a></p><p><a href=\"/works/dear___/support/\" class=\"link-in-paragraph\">Support</a></p>"
      },
      {
        bodyHtml: "<p>We all come to accept the absence of those we have loved, but we can still talk to them across time.</p>"
      }
    ]
  },
  views: {
    works: {
      outputPath: "works/dear___/index.html",
      metaTitle: "dear___",
      backHref: "/works/",
      backLabel: "ALL WORKS",
      layout: "works-case-study"
    },
    design: {
      outputPath: "design/dear___/index.html",
      metaTitle: "dear___ - Design Portfolio",
      backHref: "/design/",
      backLabel: "BACK TO DESIGN",
      layout: "design-case-study",
      eyebrow: "DESIGN PORTFOLIO"
    },
    swe: {
      outputPath: "swe/classic/dear___/index.html",
      metaTitle: "dear___ - Software Engineering Portfolio",
      backHref: "/swe/classic/",
      backLabel: "BACK TO SOFTWARE ENGINEERING",
      layout: "swe-classic-case-study",
      eyebrow: "SOFTWARE ENGINEERING PORTFOLIO"
    }
  },
  childPages: [
    {
      slug: "privacy",
      content: {
        title: "dear___ Privacy Policy",
        description: "Privacy Policy for dear___.",
        hero: {
          headline: "",
          metaLines: ["Last updated: June 11, 2026"]
        },
        sections: [
          {
            bodyHtml: "<p>dear___ is a private memory journaling app. This Privacy Policy explains how the app handles your photos, writings, music information, dates, and optional exhibition submissions.</p>"
          },
          {
            title: "1. Local memories",
            bodyHtml: "<p>By default, dear___ stores your memories locally on your device. These memories may include:</p><ul><li>Imported photos</li><li>Masks drawn over photos</li><li>Diary text</li><li>Photo dates and writing dates</li><li>Music titles or music-related notes</li><li>Exported memory cards</li></ul><p>We do not upload these memories to our server by default. We do not sell your data. We do not use your memories for advertising.</p>"
          },
          {
            title: "2. Photos and media access",
            bodyHtml: "<p>dear___ may ask for permission to access photos so you can import images into the app or save exported memory cards. The app uses this access only for features you choose to use.</p>"
          },
          {
            title: "3. Notifications",
            bodyHtml: "<p>dear___ may send optional reminders, such as on this day memories or weekly memory reminders. These notifications are based on your memories and settings. Notification content is designed to avoid showing private photo or diary details on the lock screen.</p><p>You can turn off notifications at any time in the app or in iOS Settings.</p>"
          },
          {
            title: "4. Exhibition submissions",
            bodyHtml: "<p>If you choose to submit memories to a dear___ exhibition, the app may prepare a local submission package as a .zip file. You choose which memories to include, save the .zip file, and manually upload it through a Google Form.</p><p>The package may include selected materials, such as:</p><ul><li>Exported memory cards</li><li>Masked images or cover masks</li><li>Optional original photos</li><li>Diary text</li><li>Date information</li><li>Music information or audio files</li><li>Consent information</li><li>A metadata JSON file describing the submission</li></ul><p>Submission is optional. Before creating the package, you will be shown what materials may be included. Original photos should not be submitted unless you explicitly choose to include them. If you choose to let viewers erase the cover, the package may include both the original photo and its cover mask. If you choose not to include the original photo, the app may include a covered image instead.</p><p>Exhibition submissions may be reviewed, stored, and displayed as part of the dear___ exhibition only according to the permissions you provide in the submission form.</p>"
          },
          {
            title: "5. Third-party services",
            bodyHtml: "<p>If you submit memories through a Google Form, email, or another external service, your submitted materials may also be handled according to that service's privacy policy. If the Google Form asks for contact information, such as your name or email address, that information is provided by you through Google Form.</p><p>If you connect Apple Music, dear___ may store Apple Music song information, such as song IDs, titles, and artist names, as memory metadata. Apple Music search and playback are handled by Apple MusicKit. dear___ does not receive your Apple Music account credentials.</p><p>dear___ does not use advertising SDKs and does not track you across apps or websites.</p>"
          },
          {
            title: "6. iCloud sync",
            bodyHtml: "<p>If you turn on iCloud sync, your album data may be copied to your own iCloud account so it can sync through Apple's services. This sync is controlled by your Apple ID, iCloud settings, and Apple's privacy practices. dear___ does not operate its own iCloud server and does not directly access the contents of your iCloud account.</p>"
          },
          {
            title: "7. In-app purchases",
            bodyHtml: "<p>dear___ may offer optional consumable in-app purchases to support the project. Purchases are processed by Apple. dear___ does not receive your payment card details.</p>"
          },
          {
            title: "8. Data deletion",
            bodyHtml: "<p>You can delete local memories inside the app by deleting the relevant memory or removing the app from your device.</p><p>If you submitted materials to an exhibition and want to request deletion, contact us at <a href=\"mailto:roberttqwei@gmail.com\" class=\"link-in-paragraph\">roberttqwei@gmail.com</a>.</p>"
          },
          {
            title: "9. Changes to this policy",
            bodyHtml: "<p>We may update this Privacy Policy if the app changes. The updated version will be posted on this page with a new Last updated date.</p>"
          },
          {
            title: "10. Contact",
            bodyHtml: "<p>For privacy questions, deletion requests, or support, contact:</p><p><a href=\"mailto:roberttqwei@gmail.com\" class=\"link-in-paragraph\">roberttqwei@gmail.com</a></p>"
          }
        ]
      },
      views: {
        works: {
          outputPath: "works/dear___/privacy/index.html",
          metaTitle: "dear___ - Privacy",
          layout: "plain-text-page"
        }
      }
    },
    {
      slug: "support",
      content: {
        title: "Support",
        description: "Support for dear___.",
        hero: {
          headline: "",
          metaLines: []
        },
        sections: [
          {
            bodyHtml: "<p>For support, questions, feedback, privacy requests, or exhibition submission issues, contact:</p><p><a href=\"mailto:roberttqwei@gmail.com\" class=\"link-in-paragraph\">roberttqwei@gmail.com</a></p>"
          },
          {
            title: "Common questions",
            blocks: [
              {
                title: "Where are my memories stored?",
                bodyHtml: "<p>By default, memories are stored locally on your device.</p>"
              },
              {
                title: "Does dear___ upload my photos or diary text?",
                bodyHtml: "<p>Not by default. Your memories are only shared if you choose to export them or submit them to an exhibition.</p>"
              },
              {
                title: "How do I delete a memory?",
                bodyHtml: "<p>Open the memory in the app and delete it from your local library. You can also remove all local app data by deleting the app from your device.</p>"
              },
              {
                title: "How do exhibition submissions work?",
                bodyHtml: "<p>If you choose to submit to an exhibition, dear___ may create a .zip submission package containing selected memory materials. You choose which memories and materials to include, save the .zip file, and manually upload it through the Google Form.</p>"
              },
              {
                title: "How does iCloud sync work?",
                bodyHtml: "<p>If you turn on iCloud sync, your album data may sync through your own iCloud account. You can turn this off in the app settings.</p>"
              },
              {
                title: "How do support purchases work?",
                bodyHtml: "<p>Optional support purchases are processed by Apple. dear___ does not receive your payment card details.</p>"
              },
              {
                title: "How do I request removal of an exhibition submission?",
                bodyHtml: "<p>Email <a href=\"mailto:roberttqwei@gmail.com\" class=\"link-in-paragraph\">roberttqwei@gmail.com</a> with the submission information you want removed.</p>"
              },
              {
                title: "How do I turn off notifications?",
                bodyHtml: "<p>You can turn off memory reminders in the app settings or disable notifications for dear___ in iOS Settings.</p>"
              }
            ]
          }
        ]
      },
      views: {
        works: {
          outputPath: "works/dear___/support/index.html",
          metaTitle: "dear___ - Support",
          layout: "plain-text-page"
        }
      }
    }
  ]
};
