// scripts/render-works.js developed by Bob Tianqi Wei
const fs = require("fs");
const path = require("path");
const { indexSections, fineArtColumns, musicColumns, pages } = require("./works-data");

const repoRoot = path.resolve(__dirname, "..");

function ensureDir(filePath) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
}

function writeFile(relativePath, content) {
  const outputPath = path.join(repoRoot, relativePath);
  ensureDir(outputPath);
  fs.writeFileSync(outputPath, content);
}

function isExternal(href) {
  return /^https?:\/\//.test(href);
}

function nav(currentWorks = true) {
  return `  <div data-collapse="small" data-animation="over-right" data-duration="400" id="navigation" data-easing="ease" data-easing2="ease" role="banner" class="navigation w-nav">
    <div class="navigation-items">
      <a href="/" class="logo-link w-nav-brand"><img src="/images/1b.png" width="42" height="Auto" alt="" sizes="(max-width: 479px) 100vw, 42px" srcset="/images/1b-p-500.png 500w, /images/1b.png 785w" class="logo-image"></a>
      <div class="navigation-wrap">
        <nav role="navigation" class="navigation-items w-nav-menu">
          <a href="/" class="navigation-item w-nav-link">Home</a>
          <a href="/vision/" class="navigation-item w-nav-link">VISION</a>
          <a href="/works/all-works/" class="navigation-item w-nav-link${currentWorks ? " w--current" : ""}">WORKs</a>
          <a href="/about/" class="navigation-item w-nav-link">About</a>
        </nav>
        <div class="menu-button w-nav-button"><img src="/images/menu-icon_1menu-icon.png" width="22" alt="" class="menu-icon"></div>
      </div>
    </div>
  </div>`;
}

function footer() {
  return `  <div class="footer-wrap">
    <div>
      <div>Bob Tianqi Wei&nbsp; 魏 天祺</div>
    </div>
    <div class="footer-links">
      <div class="text-block-83">Copyright © 2024 TIANQI&nbsp;ROBERT WEI. All rights reserved.</div>
    </div>
  </div>`;
}

function scripts() {
  return `  <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=63004a13914e30681af6d7b7" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="/js/webflow.js" type="text/javascript"></script>`;
}

function pageShell({ title, description, bodyClass = "", body }) {
  return `<!DOCTYPE html><!-- Generated by scripts/render-works.js -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>${title}</title>
  <meta content="${description || title}" name="description">
  <meta content="${title}" property="og:title">
  <meta content="${description || title}" property="og:description">
  <meta content="${title}" property="twitter:title">
  <meta content="${description || title}" property="twitter:description">
  <meta property="og:type" content="website">
  <meta content="summary_large_image" name="twitter:card">
  <meta content="width=device-width, initial-scale=1" name="viewport">
  <link href="/css/normalize.css" rel="stylesheet" type="text/css">
  <link href="/css/webflow.css" rel="stylesheet" type="text/css">
  <link href="/css/bobtianqiwei.webflow.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" type="text/javascript"></script>
  <script type="text/javascript">WebFont.load({google:{families:["Montserrat:100,100italic,200,200italic,300,300italic,400,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic","Droid Sans:400,700","Open Sans:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic","Changa One:400,400italic"]}});</script>
  <script type="text/javascript">!function(o,c){var n=c.documentElement,t=" w-mod-";n.className+=t+"js",("ontouchstart" in o||o.DocumentTouch&&c instanceof DocumentTouch)&&(n.className+=t+"touch")}(window,document);</script>
  <link href="/images/favicon.png" rel="shortcut icon" type="image/x-icon">
  <link href="/images/webclip.png" rel="apple-touch-icon">
  <script async="" src="https://www.googletagmanager.com/gtag/js?id=G-WZFMQV77LB"></script>
  <script type="text/javascript">window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','G-WZFMQV77LB',{'anonymize_ip':true});</script>
  <style>
  .w-background-video,
  .w-background-video-elem,
  .w-background-video-elem video {
    display: block !important;
    opacity: 1 !important;
    visibility: visible !important;
    filter: none !important;
    mix-blend-mode: normal !important;
    background: transparent !important;
  }
  </style>
</head>
<body${bodyClass ? ` class="${bodyClass}"` : ""}>
${body}
${scripts()}
</body>
</html>
`;
}

function renderImage(imgSrc, extraClass = "image-100") {
  return `<img src="${imgSrc}" loading="lazy" alt="" class="${extraClass}">`;
}

function renderAnchorCard(item, titleClass = "work-page-project-name", imageClass = "image-38") {
  const target = isExternal(item.href) ? ' target="_blank"' : "";
  const script = item.lightbox
    ? `\n            <script type="application/json" class="w-json">${JSON.stringify(item.lightbox, null, 2)}</script>`
    : "";
  const href = item.lightbox ? "#" : item.href;
  const className = item.lightbox ? "lightbox-link w-inline-block w-lightbox" : item.className;
  return `        <div class="w-container">
          <a href="${href}"${target} class="${className}">${renderImage(item.image, imageClass)}
            <div class="${titleClass}">${item.contentHtml}</div>${script}
          </a>
        </div>`;
}

function renderThreeColumnSection(items, heading) {
  const columns = [[], [], []];
  items.forEach((item, index) => {
    columns[index % 3].push(renderAnchorCard(item));
  });
  return `    <h1 class="big-title-3">${heading}</h1>
    <div class="work-columns w-row">
      <div class="column-13 w-col w-col-4">
${columns[0].join("\n")}
      </div>
      <div class="column-14 w-col w-col-4">
${columns[1].join("\n")}
      </div>
      <div class="column-15 w-col w-col-4">
${columns[2].join("\n")}
      </div>
    </div>`;
}

function renderFineArt(columns) {
  return `    <h1 id="works-art" class="works-page-heading">FINE ART</h1>
    <div class="work-columns w-row">
      <div class="column-10 w-col w-col-4">
${columns[0].map((item) => renderAnchorCard(item)).join("\n")}
      </div>
      <div class="column-11 w-col w-col-4">
${columns[1].map((item) => renderAnchorCard(item)).join("\n")}
      </div>
      <div class="column-12 w-col w-col-4">
${columns[2].map((item) => renderAnchorCard(item)).join("\n")}
      </div>
    </div>`;
}

function renderEssentials(items) {
  const rows = [];
  for (let index = 0; index < items.length; index += 2) {
    const rowItems = items.slice(index, index + 2);
    rows.push(`      <div class="work-essentials-columns w-row">
${rowItems.map((item) => `        <div class="work-column w-col w-col-6">
          <a href="${item.href}" class="work-image-link w-inline-block">
            <div class="w-layout-blockcontainer w-container">${renderImage(item.image)}
              <div class="project-name-link">${item.contentHtml}</div>
            </div>
          </a>
        </div>`).join("\n")}
      </div>`);
  }
  return `    <h1 id="work-essentials" class="works-page-heading">ESSENTIALS</h1>
    <div class="work-essentials-copy">
${rows.join("\n")}
    </div>`;
}

function renderResearch(items) {
  return `    <h1 id="works-research" class="works-page-heading">RESEARCH</h1>
${items.map((item) => {
    const target = isExternal(item.href) ? ' target="_blank"' : "";
    return `    <a href="${item.href}"${target} class="link-100 w-inline-block">
      <div class="w-layout-grid grid-research">${renderImage(item.image)}
        <div class="research-cards-text">${item.contentHtml}</div>
      </div>
    </a>`;
  }).join("\n")}`;
}

function renderMusic(columns) {
  return `    <div class="w-layout-hflex">
      <h1 id="works-music" class="works-page-heading">MUSIC</h1>
      <div class="w-layout-hflex flex-block-in-works-page-heading">
        <a href="https://www.youtube.com/channel/UCfxLPK0-77H4iC3pHukSrIg" target="_blank" class="works-page-heading-link">YouTube</a>
        <a href="https://space.bilibili.com/39406265?spm_id_from=333.1007.0.0" target="_blank" class="works-page-heading-link">Bilibili</a>
      </div>
    </div>
    <div class="music-columns-on-work-page w-row">
${columns.map((items) => `      <div class="work-column w-col w-col-4 w-col-small-4">
${items.map((item) => `        <a href="${item.href}" target="_blank" class="music-link-block w-inline-block">
          <div class="music-link-container w-container">${renderImage(item.image, item.imageClass)}
            <div class="music-title">${item.titleHtml}</div>
            <div class="music-name-block">${item.nameHtml}</div>
          </div>
        </a>`).join("\n")}
      </div>`).join("\n")}
    </div>`;
}

function renderExperiments(items) {
  const remainder = items.length % 6;
  const emptyCount = remainder === 0 ? 0 : 6 - remainder;
  return `    <h1 id="works-experiments" class="works-page-heading">EXPERIMENTS <strong class="beta">beta</strong></h1>
    <div class="work-columns w-row">
${items.map((item, index) => `      <div class="${index < 3 ? ["column-13","column-14","column-15"][index] + " " : ""}w-col w-col-2">
        <a href="${item.href}" class="project-link-block w-inline-block">
          <div class="w-container">${renderImage(item.image, "image-100")}
            <div class="work-page-project-name">${item.contentHtml}</div>
          </div>
        </a>
      </div>`).join("\n")}
${Array.from({ length: emptyCount }, () => '      <div class="w-col w-col-2"></div>').join("\n")}
    </div>`;
}

function renderAllWorks() {
  const body = `${nav()}
  <article class="work-page-div-block">
    <h1 id="works-head" class="works-page">WORKS</h1>
    <div class="work-essentials-columns w-row">
      <div class="w-col w-col-6">
        <h1 class="works-page-heading">CATALOG</h1>
        <h1 class="works-page-catalog">
          <a href="#work-essentials" class="works-catalog-link">ESSENTIALS</a><br>
          <a href="#works-research" class="works-catalog-link">RESEARCH</a><br>
          <a href="#works-design" class="works-catalog-link">DESIGN &amp; ENGINEERING<br></a>
          <a href="#works-art" class="works-catalog-link">FINE ART</a><br>
          <a href="#works-music" class="works-catalog-link">MUSIC</a><br>
          <a href="#works-experiments" class="works-catalog-link">EXPERIMENTS <strong class="beta">beta</strong></a>
        </h1>
      </div>
      <div class="w-col w-col-6">
        <h1 class="works-page-heading">PORTFOLIOS</h1>
        <h1 class="works-page-catalog">
          <a href="/design/" class="works-catalog-link">DESIGN PORTFOLIO <strong class="beta">beta</strong></a><br>
          <a href="/swe/" class="works-catalog-link">SOFTWARE ENGINEERING PORTFOLIO <strong class="beta">beta</strong></a>
        </h1>
      </div>
    </div>
${renderEssentials(indexSections["ESSENTIALS"])}
${renderResearch(indexSections["RESEARCH"])}
    <h1 id="works-design" class="works-page-heading">DESIGN &amp; ENGINEERING</h1>
${renderThreeColumnSection(indexSections["TANGIBLE SYSTEMS"], "TANGIBLE SYSTEMS")}
${renderThreeColumnSection(indexSections["DIGITAL INTERFACES"], "DIGITAL INTERFACES")}
${renderFineArt(fineArtColumns)}
${renderMusic(musicColumns)}
${renderExperiments(indexSections["EXPERIMENTS"])}
  </article>
  <div class="all-works-section">
    <a href="#navigation" class="back-to-top w-inline-block"><img src="/images/回到顶部.png" loading="lazy" width="50" height="50" alt="" class="back-to-top-image"></a>
  </div>
${footer()}`;

  return pageShell({
    title: "Works - Bob Tianqi Wei",
    description: "Bob Tianqi Wei's works: research, design, engineering, fine art, and music.",
    bodyClass: "body-4",
    body
  });
}

function renderPublicationPage(page) {
  const sections = page.sections.map((section) => `    <div class="big-title-2">${section.title}</div>
    ${section.html}`).join("\n");
  const body = `${nav(false)}
  <div class="work-detail-page-container">
    <div class="w-layout-grid project-overview-grid">
      <h1 class="heading-black-2">${page.heading}</h1>
      <div class="paragraph-title-black">${page.metaHtml}</div>
    </div>
${sections}
  </div>
  <a href="/works/all-works/" class="all-works w-inline-block">
    <h1 class="all-works-head-black">ALL WORKS</h1>
  </a>
${footer()}
  <a href="#navigation" class="back-to-top w-inline-block"><img src="/images/回到顶部.png" loading="lazy" width="50" height="50" alt="" class="back-to-top-image"></a>`;
  return pageShell({ title: page.metaTitle, body });
}

function renderLegacyHeroPage(page) {
  const slides = page.slides.map((slide) => `        <div class="w-slide">${renderImage(slide)}</div>`).join("\n");
  const body = `${nav(false)}
  <div class="${page.heroClass}">
    <div class="work-detail-page-container">
      <div class="w-layout-grid project-overview-grid">
        <div>
          <h1 class="heading-white-old">${page.heading}</h1>
          <div class="paragraph-title-white">${page.metaHtml}</div>
        </div>
      </div>
    </div>
  </div>
  <div class="work-page-content-section">
${page.videoEmbed}
    ${page.introHtml}
    <div data-delay="4000" data-animation="slide" class="slider w-slider" data-autoplay="false" data-easing="ease" data-hide-arrows="false" data-disable-swipe="false" data-autoplay-limit="0" data-nav-spacing="3" data-duration="500" data-infinite="true">
      <div class="w-slider-mask">
${slides}
      </div>
      <div class="w-slider-arrow-left"><div class="w-icon-slider-left"></div></div>
      <div class="w-slider-arrow-right"><div class="w-icon-slider-right"></div></div>
      <div class="slide-nav w-slider-nav w-slider-nav-invert"></div>
    </div>
  </div>
  <div class="all-works-section">
    <a href="/works/all-works/" class="all-works w-inline-block">
      <h1 class="all-works-head-black">ALL WORKS</h1>
    </a>
    <a href="#navigation" class="back-to-top w-inline-block"><img src="/images/回到顶部.png" loading="lazy" width="50" height="50" alt="" class="back-to-top-image"></a>
  </div>
${footer()}`;
  return pageShell({ title: page.metaTitle, body });
}

function renderAlbumPage(page) {
  const videos = page.videos.map((videoUrl, index) => `    <div class="video-embed-big w-embed w-iframe"><iframe width="100%" height="100%" src="${videoUrl}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe></div>
    <p class="paragraph-light">${index}<br></p>`).join("\n");
  const slides = page.slides.map((slide) => `        <div class="w-slide">${renderImage(slide)}</div>`).join("\n");
  const body = `${nav(false)}
  <div class="work-detail-page-container">
    <div class="w-layout-grid project-overview-grid">
      <h1 class="heading-black-big">${page.heading}</h1>
      <div class="paragraph-title-black">${page.metaHtml}</div>
    </div>
    ${page.introHtml}
${videos}
    <div class="big-title-2">Album</div>
    <div data-delay="4000" data-animation="slide" class="slider-auto w-slider" data-autoplay="true" data-easing="ease" data-hide-arrows="false" data-disable-swipe="false" data-autoplay-limit="0" data-nav-spacing="3" data-duration="500" data-infinite="true">
      <div class="mask w-slider-mask">
${slides}
      </div>
      <div class="left-arrow w-slider-arrow-left"><div class="w-icon-slider-left"></div></div>
      <div class="right-arrow w-slider-arrow-right"><div class="w-icon-slider-right"></div></div>
      <div class="slide-nav-3 w-slider-nav"></div>
    </div>
  </div>
  <a href="/works/all-works/" class="all-works w-inline-block">
    <h1 class="all-works-head-black">ALL WORKS</h1>
  </a>
${footer()}
  <a href="#navigation" class="back-to-top w-inline-block"><img src="/images/回到顶部.png" loading="lazy" width="50" height="50" alt="" class="back-to-top-image"></a>`;
  return pageShell({ title: page.metaTitle, body });
}

function renderPage(page) {
  if (page.layout === "publication") return renderPublicationPage(page);
  if (page.layout === "legacy-hero") return renderLegacyHeroPage(page);
  if (page.layout === "album") return renderAlbumPage(page);
  throw new Error(`Unsupported page layout: ${page.layout}`);
}

writeFile("works/all-works/index.html", renderAllWorks());

Object.values(pages).forEach((page) => {
  writeFile(page.outputPath, renderPage(page));
});
